name: build-action
on:
    push

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{matrix.os}}
        steps:
        - name: Check repository
          uses: actions/checkout@v3

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        #Executed on Linux & macOS
        - name: Setup Docker
          if: matrix.os != 'windows-latest'
          uses: docker-practice/actions-setup-docker@master

        - name: Gradle build
          if: matrix.os != 'windows-latest'
          run: ./gradlew build

        #Executed only on Windows
        - name: Gradle build (without Test)
          if: matrix.os == 'windows-latest'
          run: ./gradlew build -x test
