# Virtual Device Configuration Properties
virtdevice.log.level=${VIRTDEVICE_LOG_LEVEL}
virtdevice.client.pool.size=${VIRTDEVICE_CLIENT_POOL_SIZE}
virtdevice.hawkbit.tenant=${VIRTDEVICE_HAWKBIT_TENANT}
virtdevice.hawkbit.controller.id=${VIRTDEVICE_HAWKBIT_CONTROLLER_ID}
virtdevice.hawkbit.url=${VIRTDEVICE_HAWKBIT_URL}
virtdevice.hawkbit.gateway.token=${VIRTDEVICE_HAWKBIT_GATEWAY_TOKEN}
virtdevice.starting.delay=${VIRTDEVICE_STARTING_DELAY}
virtdevice.storage.path=${VIRTDEVICE_STORAGE_PATH}
virtdevice.target.attributes=${VIRTDEVICE_TARGET_ATTRIBUTES}
virtdevice.log.message=${VIRTDEVICE_LOG_MESSAGE}
virtdevice.srv.msg.before.update=${VIRTDEVICE_SRV_MSG_BEFORE_UPDATE}
virtdevice.srv.msg.after.update=${VIRTDEVICE_SRV_MSG_AFTER_UPDATE}
virtdevice.grant.download=${VIRTDEVICE_GRANT_DOWNLOAD}
virtdevice.grant.update=${VIRTDEVICE_GRANT_UPDATE}
virtdevice.connect.timeout=${VIRTDEVICE_CONNECT_TIMEOUT}
virtdevice.call.timeout=${VIRTDEVICE_CALL_TIMEOUT}
virtdevice.read.timeout=${VIRTDEVICE_READ_TIMEOUT}
virtdevice.write.timeout=${VIRTDEVICE_WRITE_TIMEOUT}